In [1]:
import pandas as pd
import duckdb
import pyarrow.parquet as pq
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

  유동인구 기본 후보:
  t23, t24

  유동인구 세부 후보:
  t4, t5, t6, t7, t8, t9, t10, t11, t16

  생산인구 기본 후보:
  t23, t24

  생산인구 세부 후보:
  t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t16, t25, t26, t27

  유입인구 기본 후보:
  t13

  유입인구 세부 후보:
  t12, t14, t25, t26

# 유동인구 데이터부터 총 인구수 활용해 유동인구 변화율 확인

In [2]:
t23 = pd.read_parquet("../data/t23_2023_2025_all_date_final.parquet")
t24 = pd.read_parquet("../data/t24_2023_2025_all_date_final.parquet")

In [3]:
t23.columns

Index(['ETL_YMD', 'CTY_CD', 'MEGA_NM', 'CTY_NM', 'SEX_CD', 'AGE_GRP',
       'TIME_CD', 'PURPOSE', 'CNT'],
      dtype='str')

In [4]:
t24.columns

Index(['ETL_YMD', 'ADMI_CD', 'MEGA_NM', 'CTY_NM', 'ADMI_NM', 'SEX_CD',
       'AGE_GRP', 'TIME_CD', 'PURPOSE', 'CNT'],
      dtype='str')

In [5]:
t23.info()

<class 'pandas.DataFrame'>
RangeIndex: 4693040 entries, 0 to 4693039
Data columns (total 9 columns):
 #   Column   Dtype
---  ------   -----
 0   ETL_YMD  datetime64[us]
 1   CTY_CD   int64
 2   MEGA_NM  str
 3   CTY_NM   str
 4   SEX_CD   str
 5   AGE_GRP  str
 6   TIME_CD  str
 7   PURPOSE  int64
 8   CNT      float64
dtypes: datetime64[us](1), float64(1), int64(2), str(5)
memory usage: 469.9 MB

In [6]:
t24.info()

<class 'pandas.DataFrame'>
RangeIndex: 43306619 entries, 0 to 43306618
Data columns (total 10 columns):
 #   Column   Dtype
---  ------   -----
 0   ETL_YMD  datetime64[us]
 1   ADMI_CD  int64
 2   MEGA_NM  str
 3   CTY_NM   str
 4   ADMI_NM  str
 5   SEX_CD   str
 6   AGE_GRP  str
 7   TIME_CD  str
 8   PURPOSE  int64
 9   CNT      float64
dtypes: datetime64[us](1), float64(1), int64(2), str(6)
memory usage: 5.0 GB

In [7]:
t23.head()

     ETL_YMD  CTY_CD MEGA_NM   CTY_NM SEX_CD AGE_GRP TIME_CD  PURPOSE     CNT
0 2023-01-19   41133     경기도  성남시 중원구      W      04      22        1    7.37
1 2023-01-19   41133     경기도  성남시 중원구      W      01      14        6   48.39
2 2023-01-26   41135     경기도  성남시 분당구      W      04      19        1   19.36
3 2023-01-24   41135     경기도  성남시 분당구      M      07      07        1  226.48
4 2023-01-03   41131     경기도  성남시 수정구      M      08      21        6  175.34

In [8]:
t24.head()

,ETL_YMD,ADMI_CD,MEGA_NM,CTY_NM,ADMI_NM,SEX_CD,AGE_GRP,TIME_CD,PURPOSE,CNT
0,2023-01-29,41135620,경기도,성남시 분당구,야탑1동,W,05,21,0,43.02
1,2023-01-08,41131530,경기도,성남시 수정구,신흥3동,M,03,05,6,9.40
2,2023-01-20,41131540,경기도,성남시 수정구,태평1동,M,05,15,0,52.42
3,2023-01-06,41135580,경기도,성남시 분당구,서현1동,M,01,15,6,31.50
4,2023-01-22,41131530,경기도,성남시 수정구,신흥3동,M,08,21,6,7.68

- t23은 시군구 단위 데이터
- t24는 행정동 데이터