## 통신 데이터(T12, 13, 14, 16) csv → parquet로 전환

In [9]:
!pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\bbb04\appdata\local\programs\python\python312\lib\site-packages (23.0.1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\bbb04\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import glob
import os

In [ ]:
input_folder = "C:/python_course/final_project/eunbi/T13/"
output_file = os.path.join(input_folder, "T13_GG_성남시_종합.parquet")

csv_files = glob.glob(os.path.join(input_folder, "T13_GG_PURPOSE_SEXAGE_ADMI_OD_*_성남시.csv"))
csv_files.sort()

chunk_size = 100000
header = ['ETL_YMD', 'O_ADMI_CD', 'O_MEGA_NM', 'O_CTY_NM', 'O_ADMI_NM', 'O_CENTER_X', 'O_CENTER_Y', 'D_ADMI_CD', 'D_MEGA_NM', 'D_CTY_NM', 'D_ADMI_NM', 'D_CENTER_X', 'D_CENTER_Y', 'PURPOSE', 'SEX_CD', 'AGE_GRP', 'CNT'] 
dtype = {
    'ETL_YMD': str,
    'O_ADMI_CD': str,
    'O_MEGA_NM': str,
    'O_CTY_NM': str,
    'O_ADMI_NM': str,
    'O_CENTER_X': 'float64',
    'O_CENTER_Y': 'float64',
    'D_ADMI_CD': str,
    'D_MEGA_NM': str,
    'D_CTY_NM': str,
    'D_ADMI_NM': str,
    'D_CENTER_X': 'float64',
    'D_CENTER_Y': 'float64',
    'PURPOSE': str,
    'SEX_CD': str,
    'AGE_GRP': 'int16',
    'CNT': 'float64'
}

parquet_schema = pa.schema([
    ('ETL_YMD', pa.string()),
    ('O_ADMI_CD', pa.string()),
    ('O_MEGA_NM', pa.string()),
    ('O_CTY_NM', pa.string()),
    ('O_ADMI_NM', pa.string()),
    ('O_CENTER_X', pa.float64()),
    ('O_CENTER_Y', pa.float64()),
    ('D_ADMI_CD', pa.string()),
    ('D_MEGA_NM', pa.string()),
    ('D_CTY_NM', pa.string()),
    ('D_ADMI_NM', pa.string()),
    ('D_CENTER_X', pa.float64()),
    ('D_CENTER_Y', pa.float64()),
    ('PURPOSE', pa.string()),
    ('SEX_CD', pa.string()),
    ('AGE_GRP', pa.int16()),
    ('CNT', pa.float64())
])

parquet_writer = None

for file_path in csv_files:
    print(f"현재 처리 중인 파일: {os.path.basename(file_path)}")

    csv_stream = pd.read_csv(file_path, chunksize=chunk_size, names=header, dtype=dtype, low_memory=False, skiprows=1)

    for chunk in csv_stream:
            # 첫 파일의 첫 청크일 때만 writer 초기화
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(output_file, parquet_schema, compression='snappy')
            
            table = pa.Table.from_pandas(chunk, schema=parquet_schema)
            parquet_writer.write_table(table)

if parquet_writer:
    parquet_writer.close()
    print(f"최종 합병 완료! 파일 경로: {output_file}")

현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202301_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202302_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202303_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202304_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202305_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202306_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202307_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202308_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202309_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202310_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202311_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202312_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202401_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202402_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202403_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202404_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202405_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202406_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202407_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202408_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202409_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202410_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202411_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202412_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202501_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202502_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202503_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202504_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202505_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202506_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202507_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202508_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202509_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202510_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202511_성남시.csv
현재 처리 중인 파일: T13_GG_PURPOSE_SEXAGE_ADMI_OD_202512_성남시.csv
최종 합병 완료! 파일 경로: C:/python_course/final_project/eunbi/T13/T13_GG_성남시_종합.parquet

In [3]:
input_folder = "C:/python_course/final_project/eunbi/T12/"
output_file = os.path.join(input_folder, "t12_2023_2025_all.parquet")

csv_files = glob.glob(os.path.join(input_folder, "T12_GG_PURPOSE_SEXAGE_SGG_OD_*_성남시.csv"))
csv_files.sort()

chunk_size = 100000
header = ['ETL_YM', 'DOW', 'O_CTY_CD', 'O_MEGA_NM', 'O_CTY_NM', 'O_CENTER_X', 'O_CENTER_Y','D_CTY_CD','D_MEGA_NM', 'D_CTY_NM', 'D_CENTER_X', 'D_CENTER_Y', 'PURPOSE', 'SEX_CD', 'AGE_GRP', 'CNT'] 
dtype = {
    'ETL_YM': str,
    'DOW': str,
    'O_CTY_CD': str,
    'O_MEGA_NM': str,
    'O_CTY_NM': str,
    'O_CENTER_X': 'float64',
    'O_CENTER_Y': 'float64',
    'D_CTY_CD': str,
    'D_MEGA_NM': str,
    'D_CTY_NM': str,
    'D_CENTER_X': 'float64',
    'D_CENTER_Y': 'float64',
    'PURPOSE': str,
    'SEX_CD': str,
    'AGE_GRP': 'int16',
    'CNT': 'float64'
}

parquet_schema = pa.schema([
    ('ETL_YM', pa.string()),
    ('DOW', pa.string()),
    ('O_CTY_CD', pa.string()),
    ('O_MEGA_NM', pa.string()),
    ('O_CTY_NM', pa.string()),
    ('O_CENTER_X', pa.float64()),
    ('O_CENTER_Y', pa.float64()),
    ('D_CTY_CD', pa.string()),
    ('D_MEGA_NM', pa.string()),
    ('D_CTY_NM', pa.string()),
    ('D_CENTER_X', pa.float64()),
    ('D_CENTER_Y', pa.float64()),
    ('PURPOSE', pa.string()),
    ('SEX_CD', pa.string()),
    ('AGE_GRP', pa.int16()),
    ('CNT', pa.float64())
])

parquet_writer = None

for file_path in csv_files:
    print(f"현재 처리 중인 파일: {os.path.basename(file_path)}")

    csv_stream = pd.read_csv(file_path, chunksize=chunk_size, names=header, dtype=dtype, low_memory=False, skiprows=1)

    for chunk in csv_stream:
            # 첫 파일의 첫 청크일 때만 writer 초기화
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(output_file, parquet_schema, compression='snappy')
            
            table = pa.Table.from_pandas(chunk, schema=parquet_schema)
            parquet_writer.write_table(table)

if parquet_writer:
    parquet_writer.close()
    print(f"최종 합병 완료! 파일 경로: {output_file}")

현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202301_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202302_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202303_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202304_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202305_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202306_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202307_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202308_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202309_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202310_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202311_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202312_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202401_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202402_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202403_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202404_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202405_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202406_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202407_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202408_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202409_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202410_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202411_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202412_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202501_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202502_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202503_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202504_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202505_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202506_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202507_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202508_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202509_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202510_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202511_성남시.csv
현재 처리 중인 파일: T12_GG_PURPOSE_SEXAGE_SGG_OD_202512_성남시.csv
최종 합병 완료! 파일 경로: C:/python_course/final_project/eunbi/T12/t12_2023_2025_all.parquet

In [4]:
input_folder = "C:/python_course/final_project/eunbi/T14/"
output_file = os.path.join(input_folder, "t14_2023_2025_all.parquet")

csv_files = glob.glob(os.path.join(input_folder, "T14_GG_TRANS_SEXAGE_SGG_OD_*_성남시.csv"))
csv_files.sort()

chunk_size = 100000
header = ['ETL_YM', 'DOW', 'O_CTY_CD', 'O_MEGA_NM', 'O_CTY_NM', 'O_CENTER_X', 'O_CENTER_Y','D_CTY_CD','D_MEGA_NM', 'D_CTY_NM', 'D_CENTER_X', 'D_CENTER_Y', 'TRANS_GB', 'SEX_CD', 'AGE_GRP', 'CNT'] 
dtype = {
    'ETL_YM': str,
    'DOW': str,
    'O_CTY_CD': str,
    'O_MEGA_NM': str,
    'O_CTY_NM': str,
    'O_CENTER_X': 'float64',
    'O_CENTER_Y': 'float64',
    'D_CTY_CD': str,
    'D_MEGA_NM': str,
    'D_CTY_NM': str,
    'D_CENTER_X': 'float64',
    'D_CENTER_Y': 'float64',
    'TRANS_GB': 'int16',
    'SEX_CD': str,
    'AGE_GRP': 'int16',
    'CNT': 'float64'
}

parquet_schema = pa.schema([
    ('ETL_YM', pa.string()),
    ('DOW', pa.string()),
    ('O_CTY_CD', pa.string()),
    ('O_MEGA_NM', pa.string()),
    ('O_CTY_NM', pa.string()),
    ('O_CENTER_X', pa.float64()),
    ('O_CENTER_Y', pa.float64()),
    ('D_CTY_CD', pa.string()),
    ('D_MEGA_NM', pa.string()),
    ('D_CTY_NM', pa.string()),
    ('D_CENTER_X', pa.float64()),
    ('D_CENTER_Y', pa.float64()),
    ('TRANS_GB', pa.int16()),
    ('SEX_CD', pa.string()),
    ('AGE_GRP', pa.int16()),
    ('CNT', pa.float64())
])

parquet_writer = None

for file_path in csv_files:
    print(f"현재 처리 중인 파일: {os.path.basename(file_path)}")

    csv_stream = pd.read_csv(file_path, chunksize=chunk_size, names=header, dtype=dtype, low_memory=False, skiprows=1)

    for chunk in csv_stream:
            # 첫 파일의 첫 청크일 때만 writer 초기화
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(output_file, parquet_schema, compression='snappy')
            
            table = pa.Table.from_pandas(chunk, schema=parquet_schema)
            parquet_writer.write_table(table)

if parquet_writer:
    parquet_writer.close()
    print(f"최종 합병 완료! 파일 경로: {output_file}")

현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202301_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202302_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202303_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202304_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202305_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202306_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202307_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202308_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202309_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202310_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202311_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202312_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202401_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202402_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202403_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202404_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202405_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202406_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202407_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202408_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202409_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202410_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202411_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202412_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202501_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202502_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202503_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202504_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202505_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202506_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202507_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202508_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202509_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202510_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202511_성남시.csv
현재 처리 중인 파일: T14_GG_TRANS_SEXAGE_SGG_OD_202512_성남시.csv
최종 합병 완료! 파일 경로: C:/python_course/final_project/eunbi/T14/t14_2023_2025_all.parquet

In [6]:
input_folder = "C:/python_course/final_project/eunbi/T16/"
output_file = os.path.join(input_folder, "t16_2023_2025_all.parquet")

csv_files = glob.glob(os.path.join(input_folder, "T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_*_성남시.csv"))
csv_files.sort()

chunk_size = 100000
header = ['ETL_YM', 'DOW', 'D_TIME', 'D_CTY_CD','D_MEGA_NM', 'D_CTY_NM', 'D_CENTER_X', 'D_CENTER_Y', 'PURPOSE', 'SEX_CD', 'AGE_GRP', 'CNT', 'DURATION'] 
dtype = {
    'ETL_YM': str,
    'DOW': str,
    'D_TIME': 'int32',
    'D_CTY_CD': str,
    'D_MEGA_NM': str,
    'D_CTY_NM': str,
    'D_CENTER_X': 'float64',
    'D_CENTER_Y': 'float64',
    'PURPOSE': str,
    'SEX_CD': str,
    'AGE_GRP': 'int16',
    'CNT': 'float64',
    'DURATION': 'float64'
}

parquet_schema = pa.schema([
    ('ETL_YM', pa.string()),
    ('DOW', pa.string()),
    ('D_TIME', pa.int32()),
    ('D_CTY_CD', pa.string()),
    ('D_MEGA_NM', pa.string()),
    ('D_CTY_NM', pa.string()),
    ('D_CENTER_X', pa.float64()),
    ('D_CENTER_Y', pa.float64()),
    ('PURPOSE', pa.string()),
    ('SEX_CD', pa.string()),
    ('AGE_GRP', pa.int16()),
    ('CNT', pa.float64()),
    ('DURATION', pa.float64()) 
])

parquet_writer = None

for file_path in csv_files:
    print(f"현재 처리 중인 파일: {os.path.basename(file_path)}")

    csv_stream = pd.read_csv(file_path, chunksize=chunk_size, names=header, dtype=dtype, low_memory=False, skiprows=1)

    for chunk in csv_stream:
            # 첫 파일의 첫 청크일 때만 writer 초기화
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(output_file, parquet_schema, compression='snappy')
            
            table = pa.Table.from_pandas(chunk, schema=parquet_schema)
            parquet_writer.write_table(table)

if parquet_writer:
    parquet_writer.close()
    print(f"최종 합병 완료! 파일 경로: {output_file}")

현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202301_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202302_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202303_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202304_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202305_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202306_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202307_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202308_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202309_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202310_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202311_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202312_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202401_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202402_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202403_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202404_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202405_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202406_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202407_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202408_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202409_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202410_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202411_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202412_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202501_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202502_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202503_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202504_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202505_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202506_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202507_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202508_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202509_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202510_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202511_성남시.csv
현재 처리 중인 파일: T16_GG_PURPOSE_SEXAGE_DURATION_SGG_INFLOW_202512_성남시.csv
최종 합병 완료! 파일 경로: C:/python_course/final_project/eunbi/T16/t16_2023_2025_all.parquet

## 인구 데이터 결측치/이상치 확인

In [49]:
import pandas as pd
folder_path = "C:/python_course/final_project/eunbi" 
pop_df = pd.read_csv(folder_path+"/인구/population_total.csv", encoding='euc-kr')

In [50]:
pop_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   행정구역    1800 non-null   str
 1   행정동 코드  1800 non-null   int64
 2   날짜      1800 non-null   str
 3   총인구수    1800 non-null   str
 4   세대수     1800 non-null   str
 5   세대당_인구  1800 non-null   float64
dtypes: float64(1), int64(1), str(4)
memory usage: 186.5 KB

In [51]:
pop_df.head()

               행정구역      행정동 코드       날짜    총인구수    세대수  세대당_인구
0  경기도 성남시 수정구 신흥1동  4113151000  2023-01  13,150  7,928    1.66
1  경기도 성남시 수정구 신흥2동  4113152000  2023-01  19,870  7,612    2.61
2  경기도 성남시 수정구 신흥3동  4113153000  2023-01  11,223  6,537    1.72
3  경기도 성남시 수정구 태평1동  4113154000  2023-01  15,031  8,805    1.71
4  경기도 성남시 수정구 태평2동  4113155000  2023-01  14,938  7,908    1.89

In [55]:
pop_df['총인구수'] = pop_df['총인구수'].str.replace(',', '').astype(int)
pop_df['세대수'] = pop_df['세대수'].str.replace(',', '').astype(int)

In [56]:
pop_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   행정구역    1800 non-null   str
 1   행정동 코드  1800 non-null   int64
 2   날짜      1800 non-null   str
 3   총인구수    1800 non-null   int64
 4   세대수     1800 non-null   int64
 5   세대당_인구  1800 non-null   float64
dtypes: float64(1), int64(3), str(2)
memory usage: 166.8 KB

In [58]:
display(pop_df['세대수'].describe())
display(pop_df['총인구수'].describe())
display(pop_df['세대당_인구'].describe())

count     1800.000000
mean      8196.327778
std       3706.495872
min       1523.000000
25%       6335.750000
50%       7598.500000
75%      10757.000000
max      18849.000000
Name: 세대수, dtype: float64

count     1800.000000
mean     18309.948889
std       8816.316881
min       2911.000000
25%      11904.000000
50%      16594.500000
75%      24900.000000
max      46396.000000
Name: 총인구수, dtype: float64

count    1800.000000
mean        2.227244
std         0.379348
min         1.540000
25%         1.940000
50%         2.220000
75%         2.480000
max         3.280000
Name: 세대당_인구, dtype: float64

In [66]:
pop_df[pop_df.duplicated(subset=['행정구역', '행정동 코드', '날짜', '총인구수', '세대수', '세대당_인구'], keep=False)]

Empty DataFrame
Columns: [행정구역, 행정동 코드, 날짜, 총인구수, 세대수, 세대당_인구]
Index: []

## 기업 데이터 결측치/이상치 확인

In [67]:
new_df = pd.read_csv(folder_path+"/기업/new_corp_total.csv")

In [68]:
new_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3367 entries, 0 to 3366
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             3367 non-null   str
 1   sido_nm          3367 non-null   str
 2   sigun_nm         3367 non-null   str
 3   admi_nm          3367 non-null   str
 4   dong_code        3367 non-null   int64
 5   induty_pri_cd    3367 non-null   str
 6   induty_pri_nm    3367 non-null   str
 7   induty_med_cd    3367 non-null   str
 8   induty_med_nm    3367 non-null   str
 9   ncr_crp_comp_cn  3367 non-null   int64
dtypes: int64(2), str(8)
memory usage: 654.5 KB

In [69]:
new_df['ncr_crp_comp_cn'].describe()

count    3367.000000
mean        1.275616
std         0.839147
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max        12.000000
Name: ncr_crp_comp_cn, dtype: float64

In [72]:
new_df[new_df.duplicated(subset=['date','dong_code','induty_pri_nm','induty_med_nm'], keep=False)]

Empty DataFrame
Columns: [date, sido_nm, sigun_nm, admi_nm, dong_code, induty_pri_cd, induty_pri_nm, induty_med_cd, induty_med_nm, ncr_crp_comp_cn]
Index: []