In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
pd.set_option('display.float_format', '{:.0f}'.format)

In [7]:
file_path = "../Data/transactions_total.csv"

print(os.path.exists(file_path))

trans_df  = pd.read_csv(file_path, encoding = 'cp949')

trans_df .head(2)

True

           시군구  법정동  유형  용도지역  전용/연면적(㎡)   건축물주용도  거래금액(만원)  층     계약연월
0  경기도 성남시 분당구  구미동  집합  근린상업         30  제2종근린생활     69500  1  2023-01
1  경기도 성남시 분당구  금곡동  집합  중심상업         45  제2종근린생활     69000  1  2023-01

In [12]:
trans_df['층'] = trans_df['층'].astype('object')
trans_df.loc[(trans_df['유형'] == '집합') & (trans_df['층'].isna()), '층'] = 'unknown'
trans_df.loc[(trans_df['유형'] == '일반') & (trans_df['층'].isna()), '층'] = 'whole_building'

In [13]:
trans_df.loc[(trans_df['유형'] == '집합') & (trans_df['층'] == 'unknown')]

,시군구,법정동,유형,용도지역,전용/연면적(㎡),건축물주용도,거래금액(만원),층,계약연월
3,경기도 성남시 분당구,서현동,집합,근린상업,76,제1종근린생활,37000,unknown,2023-01
5,경기도 성남시 분당구,서현동,집합,근린상업,131,제1종근린생활,64247,unknown,2023-01
6,경기도 성남시 분당구,서현동,집합,준주거,23,제2종근린생활,23000,unknown,2023-01
7,경기도 성남시 분당구,서현동,집합,중심상업,35,업무,13700,unknown,2023-01
8,경기도 성남시 분당구,서현동,집합,중심상업,67,제2종근린생활,20500,unknown,2023-01
...,...,...,...,...,...,...,...,...,...
3022,경기도 성남시 분당구,수내동,집합,준주거,17,제1종근린생활,51000,unknown,2025-12
3034,경기도 성남시 분당구,정자동,집합,근린상업,22,제1종근린생활,4800,unknown,2025-12
3036,경기도 성남시 분당구,정자동,집합,제3종일반주거,41,제1종근린생활,53000,unknown,2025-12
3038,경기도 성남시 분당구,정자동,집합,중심상업,864,업무,645000,unknown,2025-12
3049,경기도 성남시 중원구,금광동,집합,제2종일반주거,21,제2종근린생활,21900,unknown,2025-12

In [36]:
# 상·하위 10% 중에서도 극단인 값
lower_10 = np.percentile(trans_df['거래금액(만원)'], 10)
upper_90 = np.percentile(trans_df['거래금액(만원)'], 90)

upper_subset = trans_df[trans_df['거래금액(만원)'] >= upper_90]
q1_u = upper_subset['거래금액(만원)'].quantile(0.25)
q3_u = upper_subset['거래금액(만원)'].quantile(0.75)
iqr_u = q3_u - q1_u
upper_extreme = upper_subset[upper_subset['거래금액(만원)'] > (q3_u + 1.5 * iqr_u)]

lower_subset = trans_df[trans_df['거래금액(만원)'] <= lower_10]
q1_l = lower_subset['거래금액(만원)'].quantile(0.25)
q3_l = lower_subset['거래금액(만원)'].quantile(0.75)
iqr_l = q3_l - q1_l
lower_extreme = lower_subset[lower_subset['거래금액(만원)'] < (q1_l - 0.5 * iqr_l)] 
# q1_l - 1.5 * iqr_l일 경우, 하위 10% 중에서도 극단인 값이 0건으로 나타남. 따라서 하위 극단값 기준을 q1_l - 0.5 * iqr_l로 완화하여 적용함.

In [34]:
upper_extreme

,시군구,법정동,유형,용도지역,전용/연면적(㎡),건축물주용도,거래금액(만원),층,계약연월
223,경기도 성남시 분당구,백현동,일반,중심상업,87902,업무,69135000,whole_building,2023-04
355,경기도 성남시 분당구,운중동,일반,준주거,3332,제2종근린생활,2150000,whole_building,2023-05
403,경기도 성남시 분당구,구미동,집합,근린상업,1645,업무,1307037,unknown,2023-06
404,경기도 성남시 분당구,구미동,집합,근린상업,1904,업무,1777610,unknown,2023-06
405,경기도 성남시 분당구,구미동,집합,근린상업,2447,업무,2117600,unknown,2023-06
406,경기도 성남시 분당구,구미동,집합,근린상업,2764,업무,2320025,unknown,2023-06
604,경기도 성남시 분당구,삼평동,집합,준주거,1567,업무,2077567,5,2023-08
767,경기도 성남시 분당구,삼평동,집합,준주거,680,업무,1325000,unknown,2023-10
769,경기도 성남시 분당구,삼평동,집합,준주거,1664,업무,1786900,unknown,2023-10
851,경기도 성남시 분당구,서현동,일반,중심상업,17439,업무,9460000,whole_building,2023-11
1314,경기도 성남시 수정구,시흥동,일반,자연녹지,1774,업무,3823800,whole_building,2024-04
1315,경기도 성남시 수정구,시흥동,일반,자연녹지,11960,교육연구,9067800,whole_building,2024-04
1558,경기도 성남시 분당구,서현동,일반,자연녹지,1736,기타,3942440,whole_building,2024-07
1719,경기도 성남시 분당구,삼평동,일반,중심상업,17321,업무,12587000,whole_building,2024-09
1795,경기도 성남시 분당구,서현동,일반,중심상업,23824,제1종근린생활,12470000,whole_building,2024-10
1940,경기도 성남시 분당구,삼평동,일반,준주거,57461,교육연구,40000000,whole_building,2024-12
2016,경기도 성남시 수정구,수진동,일반,준주거,3634,제2종근린생활,1560000,whole_building,2024-12
2034,경기도 성남시 중원구,상대원동,집합,용도미지정,2868,기타,1858048,unknown,2024-12
2342,경기도 성남시 분당구,서현동,일반,중심상업,13815,업무,10000000,whole_building,2025-05
2424,경기도 성남시 분당구,삼평동,일반,준주거,67024,업무,43278408,whole_building,2025-06
2682,경기도 성남시 수정구,태평동,일반,자연녹지,606,제2종근린생활,1550445,whole_building,2025-08
2718,경기도 성남시 분당구,백현동,일반,중심상업,197237,업무,198204140,whole_building,2025-09
2812,경기도 성남시 분당구,서현동,일반,중심상업,5398,교육연구,2860000,whole_building,2025-10
2840,경기도 성남시 분당구,운중동,일반,준주거,2598,제1종근린생활,1700000,whole_building,2025-10
2904,경기도 성남시 분당구,삼평동,일반,준주거,49679,업무,36070000,whole_building,2025-11
3006,경기도 성남시 분당구,삼평동,일반,준주거,15537,업무,11750000,whole_building,2025-12
3040,경기도 성남시 수정구,수진동,일반,준주거,3634,제1종근린생활,1677520,whole_building,2025-12

In [35]:
lower_extreme

,시군구,법정동,유형,용도지역,전용/연면적(㎡),건축물주용도,거래금액(만원),층,계약연월
249,경기도 성남시 분당구,수내동,집합,준주거,4,제1종근린생활,1800,unknown,2023-04
397,경기도 성남시 중원구,성남동,집합,일반상업,4,판매,200,4,2023-05
521,경기도 성남시 분당구,백현동,일반,자연녹지,67,제2종근린생활,1629,whole_building,2023-07
711,경기도 성남시 분당구,야탑동,집합,중심상업,6,판매,1800,2,2023-09
815,경기도 성남시 분당구,구미동,집합,근린상업,13,제1종근린생활,1200,2,2023-11
891,경기도 성남시 중원구,성남동,집합,일반상업,5,판매,500,unknown,2023-11
1009,경기도 성남시 중원구,금광동,집합,준주거,15,판매,1400,unknown,2024-01
1376,경기도 성남시 분당구,서현동,집합,근린상업,5,제1종근린생활,1800,unknown,2024-05
1559,경기도 성남시 분당구,서현동,집합,근린상업,9,제1종근린생활,1000,unknown,2024-07
2283,경기도 성남시 분당구,야탑동,집합,중심상업,10,판매,1500,unknown,2025-04
2495,경기도 성남시 중원구,성남동,집합,일반상업,5,판매,1000,2,2025-06
2872,경기도 성남시 중원구,상대원동,집합,제3종일반주거,7,제1종근린생활,1750,unknown,2025-10

- 최솟값: 4㎡(1.21평), 최댓값: 197,237㎡(약 59,664평)
- 상업용 부동산 거래 면적 4㎡은 너무 작음. 전용/연면적(㎡)이 작을수록 거래금액도 비정상적으로 낮음(거래금액-면적: 상관관계 보면서 극단값 보기)

# 13번 602번 
| 시군구 | 법정동 | 유형 | 용도지역 | 전용/연면적(㎡) | 건축물주용도 | 거래금액(만원) | 층 | 계약연월 |
|---|---|---|---|---:|---|---:|---:|---|
|경기도 성남시 분당구|	삼평동|	집합|	준주거|	717|	업무|	950288|	w5	|2023-08|

# 11번 423번 
| 시군구 | 법정동 | 유형 | 용도지역 | 전용/연면적(㎡) | 건축물주용도 | 거래금액(만원) | 층 | 계약연월 |
|---|---|---|---|---:|---|---:|---:|---|
| 경기도 성남시 분당구 | 삼평동 | 집합 | 준주거 | 1051 | 교육연구 | 1251900 | 5 | 2023-06 |

- 거래 금액 = 1251900만원 (약125억)
- 면적 = 1051 ㎡ = 약, 317평
- 1평당 = 39,376,900원 (약 3천 9백)

In [ ]:
# 2) 면적이 비슷한 거래끼리 비교: 1051㎡ 기준 ±20%
# 여러개 비슷한 걸로 봐서는 이상치로 보기 어렵
target_area = 1051

similar_area = trans_df[
    (trans_df['전용/연면적(㎡)'].between(target_area * 0.8, target_area * 1.2)) &
    (trans_df['유형'] == '집합')
].copy()

similar_area[['법정동','용도지역','건축물주용도','전용/연면적(㎡)','거래금액(만원)','층','계약연월']] \
    .sort_values('거래금액(만원)', ascending=False)

      법정동     용도지역   건축물주용도  전용/연면적(㎡)  거래금액(만원)        층     계약연월
422   삼평동      준주거     교육연구       1047   1251900        6  2023-06
423   삼평동      준주거     교육연구       1051   1251900        5  2023-06
1725  삼평동      준주거       업무        888   1250000        8  2024-09
58    삼평동      준주거       업무        940   1245000       10  2023-02
1162  삼평동      준주거       업무        846   1220560        3  2024-03
1656  삼평동      준주거     교육연구       1047   1180000  unknown  2024-08
330   삼평동      준주거     교육연구       1047   1150000  unknown  2023-05
768   삼평동      준주거       업무        846    990000  unknown  2023-10
2646  삼평동      준주거     교육연구       1036    850000  unknown  2025-08
3038  정자동     중심상업       업무        864    645000  unknown  2025-12
1408  정자동     근린상업       판매       1243    420000  unknown  2024-05
450   운중동  제1종일반주거     교육연구       1211    390200  unknown  2023-06
2145  정자동     근린상업       기타        955    361312       30  2025-02
2853  정자동     중심상업  제2종근린생활        844    260000  unknown  2025-10
2480  신흥동     일반상업  제2종근린생활        881    219100  unknown  2025-06
1509  정자동     근린상업  제1종근린생활        910    162000  unknown  2024-06
2089  수진동     일반상업  제2종근린생활        841    150000       10  2025-01

# 12번 595번 
| 시군구 | 법정동 | 유형 | 용도지역 | 전용/연면적(㎡) | 건축물주용도 | 거래금액(만원) | 층 | 계약연월 |
|---|---|---|---|---:|---|---:|---:|---|
|경기도 성남시 분당구|	백현동|	일반|	보전녹지|	498|	제1종근린생활|	1200000|	whole_building	|2023-08|

- 거래 금액 = 1200000만원 (120억)
- 면적 = 498㎡ (약 150평)
- 1평당 = 79,657,470원 (약 7천 965만)

In [28]:
target_area = 498

similar_area = trans_df[
    (trans_df['전용/연면적(㎡)'].between(target_area * 0.8, target_area * 1.2)) &
    (trans_df['유형'] == '일반') &
    (trans_df['시군구'] == '경기도 성남시 분당구') &
    (trans_df['용도지역'] == '보전녹지') &
    (trans_df['건축물주용도'] == '제1종근린생활')
].copy()

similar_area

,시군구,법정동,유형,용도지역,전용/연면적(㎡),건축물주용도,거래금액(만원),층,계약연월
180,경기도 성남시 분당구,운중동,일반,보전녹지,499,제1종근린생활,530000,whole_building,2023-03
595,경기도 성남시 분당구,백현동,일반,보전녹지,498,제1종근린생활,1200000,whole_building,2023-08
970,경기도 성남시 분당구,삼평동,일반,보전녹지,498,제1종근린생활,900000,whole_building,2024-01
2422,경기도 성남시 분당구,백현동,일반,보전녹지,556,제1종근린생활,590000,whole_building,2025-06

# 13번 602번 
| 시군구 | 법정동 | 유형 | 용도지역 | 전용/연면적(㎡) | 건축물주용도 | 거래금액(만원) | 층 | 계약연월 |
|---|---|---|---|---:|---|---:|---:|---|
|경기도 성남시 분당구|	삼평동|	집합|	준주거|	717|	업무|	950288|	5	|2023-08|

- 거래 금액 : 950288 (약 95억)
- 면적 : 717 -> 217평
- 1평당 : 43,813,777원 (약 4천 300백)

In [30]:
target_area = 717

similar_area = trans_df[
    (trans_df['전용/연면적(㎡)'].between(target_area * 0.8, target_area * 1.2)) &
    (trans_df['유형'] == '집합') &
    (trans_df['시군구'] == '경기도 성남시 분당구') &
    (trans_df['용도지역'] == '준주거') &
    (trans_df['건축물주용도'] == '업무')
].copy()

similar_area

              시군구  법정동  유형 용도지역  전용/연면적(㎡) 건축물주용도  거래금액(만원)        층     계약연월
602   경기도 성남시 분당구  삼평동  집합  준주거        717     업무    950288        5  2023-08
603   경기도 성남시 분당구  삼평동  집합  준주거        766     업무   1016103        5  2023-08
693   경기도 성남시 분당구  삼평동  집합  준주거        758     업무   1026883  unknown  2023-09
767   경기도 성남시 분당구  삼평동  집합  준주거        680     업무   1325000  unknown  2023-10
768   경기도 성남시 분당구  삼평동  집합  준주거        846     업무    990000  unknown  2023-10
900   경기도 성남시 분당구  삼평동  집합  준주거        766     업무    700000        6  2023-12
1161  경기도 성남시 분당구  삼평동  집합  준주거        680     업무    944730  unknown  2024-03
1162  경기도 성남시 분당구  삼평동  집합  준주거        846     업무   1220560        3  2024-03
2197  경기도 성남시 분당구  삼평동  집합  준주거        580     업무    750000  unknown  2025-03
2198  경기도 성남시 분당구  삼평동  집합  준주거        582     업무    750000  unknown  2025-03
2199  경기도 성남시 분당구  삼평동  집합  준주거        711     업무    800000        7  2025-03