In [2]:
import pandas as pd
import glob
import os

## 지하철 결측치 / 이상치

In [3]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\pro\final_project\Data\subway.csv"

# 파일 존재 여부 먼저 확인
print(os.path.exists(file_path))

# True가 나오면 실행
df_subway = pd.read_csv(file_path, encoding="utf-8-sig")

df_subway.head(5)

True

         월  노선명                역명  월별_승차합계  월별_하차합계
0  2023-01  분당선               가천대   182889   200114
1  2023-01  8호선               남위례   159937   165440
2  2023-01  8호선  남한산성입구(성남법원.검찰청)   349153   313708
3  2023-01  8호선             단대오거리   312021   304362
4  2023-01  8호선                모란   131234   106478

In [4]:
df_subway.shape

(850, 5)

In [5]:
df_subway.isnull().sum()

월          0
노선명        0
역명         0
월별_승차합계    0
월별_하차합계    0
dtype: int64

## 버스 결측치 / 이상치

In [2]:
import pandas as pd
import glob
import os

In [3]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\pro\final_project\Data\bus_plz.csv"

# 파일 존재 여부 먼저 확인
print(os.path.exists(file_path))

# True가 나오면 실행
df_bus = pd.read_csv(file_path, encoding="utf-8-sig")

df_bus.head(5)

True

C:\Users\cute3\AppData\Local\Temp\ipykernel_28760\2935227847.py:7: DtypeWarning: Columns (0: 정류소번호) have mixed types. Specify dtype option on import or set low_memory=False.
  df_bus = pd.read_csv(file_path, encoding="utf-8-sig")

        승하차일자 관할관청   행정동      정류소ID   정류소번호         정류소명  승차합계   초승   환승   하차
0  2023-01-01  성남시   성남동  205000120  6163.0   (구)성남동주민센터   103   99    4  106
1  2023-01-01  성남시  서현1동  206000436  7387.0      AK플라자2층   353  203  150  454
2  2023-01-01  성남시   삼평동  206000677  7034.0  H스퀘어.삼환하이펙스     1    1    0   25
3  2023-01-01  성남시   삼평동  206000677  7034.0  H스퀘어.삼환하이펙스     1    1    0   25
4  2023-01-01  성남시   삼평동  206000678  7479.0  H스퀘어.삼환하이펙스    15   14    1    2

In [4]:
df_bus.shape

(2058750, 10)

In [5]:
df_bus.isnull().sum()

승하차일자        0
관할관청         0
행정동      65110
정류소ID        0
정류소번호     2540
정류소명         6
승차합계         0
초승           0
환승           0
하차           0
dtype: int64

In [6]:
df_bus[df_bus['행정동'].isnull()]

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
17,2023-01-01,성남시,NaN,206000855,7822.0,SK.금강테라스하우스,11,10,1,24
48,2023-01-01,성남시,NaN,204000001,5008.0,고등동우체국.성남농협대왕지점,89,60,29,178
84,2023-01-01,성남시,NaN,204000256,5221.0,교보문고(마을),11,11,0,30
94,2023-01-01,성남시,NaN,205000008,6076.0,구서고.금상초교,389,378,11,244
95,2023-01-01,성남시,NaN,205000160,6074.0,구서고.금상초교,317,303,14,332
...,...,...,...,...,...,...,...,...,...,...
2058599,2025-12-31,성남시,NaN,205000016,06025,하대원동행정복지센터.영성중.검단초,406,360,46,686
2058600,2025-12-31,성남시,NaN,205000152,06024,하대원동행정복지센터.영성중.검단초,731,688,43,352
2058647,2025-12-31,성남시,NaN,204000070,05151,한국폴리텍대학.성남문화예술교육센터,27,23,4,37
2058648,2025-12-31,성남시,NaN,204000080,05149,한국폴리텍대학.성남문화예술교육센터,8,4,4,36
2058688,2025-12-31,성남시,NaN,206000342,07318,현대노블리스,0,0,0,12

In [ ]:
# 정류소 와 행정동이 모두 nan값인 행 찾기
result = df_bus[
    (df_bus['정류소명'].notna()) &
    (df_bus['행정동'].isna())
]

result

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
17,2023-01-01,성남시,NaN,206000855,7822.0,SK.금강테라스하우스,11,10,1,24
48,2023-01-01,성남시,NaN,204000001,5008.0,고등동우체국.성남농협대왕지점,89,60,29,178
84,2023-01-01,성남시,NaN,204000256,5221.0,교보문고(마을),11,11,0,30
94,2023-01-01,성남시,NaN,205000008,6076.0,구서고.금상초교,389,378,11,244
95,2023-01-01,성남시,NaN,205000160,6074.0,구서고.금상초교,317,303,14,332
...,...,...,...,...,...,...,...,...,...,...
2058599,2025-12-31,성남시,NaN,205000016,06025,하대원동행정복지센터.영성중.검단초,406,360,46,686
2058600,2025-12-31,성남시,NaN,205000152,06024,하대원동행정복지센터.영성중.검단초,731,688,43,352
2058647,2025-12-31,성남시,NaN,204000070,05151,한국폴리텍대학.성남문화예술교육센터,27,23,4,37
2058648,2025-12-31,성남시,NaN,204000080,05149,한국폴리텍대학.성남문화예술교육센터,8,4,4,36
2058688,2025-12-31,성남시,NaN,206000342,07318,현대노블리스,0,0,0,12

In [28]:
df_bus[
    (df_bus['정류소ID'] == 206000617) &
    (df_bus['정류소명'] == '성남역.보평중고등학교')
]

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
766909,2024-03-19,성남시,백현동,206000617,7557.0,성남역.보평중고등학교,68,62,6,114
766910,2024-03-19,성남시,삼평동,206000617,7557.0,성남역.보평중고등학교,68,62,6,114
786148,2024-03-30,성남시,백현동,206000617,7557.0,성남역.보평중고등학교,43,37,6,81
786149,2024-03-30,성남시,삼평동,206000617,7557.0,성남역.보평중고등학교,43,37,6,81
787889,2024-03-31,성남시,백현동,206000617,7557.0,성남역.보평중고등학교,45,26,19,85
...,...,...,...,...,...,...,...,...,...,...
2053479,2025-12-29,성남시,삼평동,206000617,07557,성남역.보평중고등학교,42,27,15,140
2055589,2025-12-30,성남시,백현동,206000617,07557,성남역.보평중고등학교,35,25,10,122
2055590,2025-12-30,성남시,삼평동,206000617,07557,성남역.보평중고등학교,35,25,10,122
2057690,2025-12-31,성남시,백현동,206000617,07557,성남역.보평중고등학교,37,28,9,106
2057691,2025-12-31,성남시,삼평동,206000617,07557,성남역.보평중고등학교,37,28,9,106

In [24]:
df_bus[
    (df_bus['정류소ID'] == 206000616) &
    (df_bus['정류소명'] == '성남역.보평중고등학교') 
]

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
766907,2024-03-19,성남시,백현동,206000616,7556.0,성남역.보평중고등학교,127,125,2,81
766908,2024-03-19,성남시,삼평동,206000616,7556.0,성남역.보평중고등학교,127,125,2,81
786146,2024-03-30,성남시,백현동,206000616,7556.0,성남역.보평중고등학교,63,39,24,40
786147,2024-03-30,성남시,삼평동,206000616,7556.0,성남역.보평중고등학교,63,39,24,40
787887,2024-03-31,성남시,백현동,206000616,7556.0,성남역.보평중고등학교,54,42,12,30
...,...,...,...,...,...,...,...,...,...,...
2053477,2025-12-29,성남시,삼평동,206000616,07556,성남역.보평중고등학교,187,157,30,88
2055587,2025-12-30,성남시,백현동,206000616,07556,성남역.보평중고등학교,194,168,26,104
2055588,2025-12-30,성남시,삼평동,206000616,07556,성남역.보평중고등학교,194,168,26,104
2057688,2025-12-31,성남시,백현동,206000616,07556,성남역.보평중고등학교,223,184,39,82
2057689,2025-12-31,성남시,삼평동,206000616,07556,성남역.보평중고등학교,223,184,39,82

In [ ]:
# 백현동쪽 버스정류장 -> 삼평동 없애기
df_bus[
    (df_bus['정류소ID'] == 206000617) &
    (df_bus['정류소명'] == '성남역.보평중고등학교') &
    (df_bus['승하차일자'] == '2024-03-30') 
]

             승하차일자 관할관청  행정동      정류소ID   정류소번호         정류소명  승차합계  초승  환승  하차
786148  2024-03-30  성남시  백현동  206000617  7557.0  성남역.보평중고등학교    43  37   6  81
786149  2024-03-30  성남시  삼평동  206000617  7557.0  성남역.보평중고등학교    43  37   6  81

In [ ]:
# 삼평동쪽 버스정류장 -> 백현동 없애기
df_bus[
    (df_bus['정류소ID'] == 206000616) &
    (df_bus['정류소명'] == '성남역.보평중고등학교') &
    (df_bus['승하차일자'] == '2024-03-19') 
]

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
766907,2024-03-19,성남시,백현동,206000616,7556.0,성남역.보평중고등학교,127,125,2,81
766908,2024-03-19,성남시,삼평동,206000616,7556.0,성남역.보평중고등학교,127,125,2,81

- 정류소ID 206000305 / 정류소번호 7159.0
    - 2023년: 정류소명 → 아름마을.이매고교.효성선경아파트.하나은행, 행정동 → 이매2동
    - 2024년: 정류소명 → 성남역.이매고교.아름마을.효성선경아파트, 행정동 → 이매2동 
- 정류소ID 206000314 / 정류소번호 7303.0
  - 2023년: 정류소명 → 아름마을.이매고교.효성선경아파트.하나은행, 행정동 → 이매2동
  - 2024년: 정류소명 → 성남역.이매고교.아름마을.효성선경아파트, 행정동 → 이매2동
- 정류소ID 206000530 / 정류소번호 7487.0
  - 2023년: 정류소명 → 백현마을2단지, 행정동 → 백현동
  - 2024년: 정류소명 → 성남역.백현마을2단지, 행정동 → 백현동
- 정류소ID 206000537 / 정류소번호 7420.0
  - 2023년: 정류소명 → 백현마을3단지, 행정동 → 백현동
  - 2024년: 정류소명 → 성남역.백현마을3단지, 행정동 → 백현동

- 정류소ID 206000616 / 정류소번호 7556.0
  - 2023년: 정류소명 → 보평중고등학교
    - 앞쪽 정류장 행정동 → 삼평동
    - 뒤쪽 정류장 행정동 → 백현동
  - 2024년: 정류소명 → 성남역.보평중고등학교
   - 행정동은 동일하게 유지 (삼평동 / 백현동)
- 정류소ID 206000617 / 정류소번호 7557.0
  - 2023년: 정류소명 → 보평중고등학교
    - 앞쪽 정류장 행정동 → 삼평동
    - 뒤쪽 정류장 행정동 → 백현동
- 2024년: 정류소명 → 성남역.보평중고등학교
   - 행정동은 동일하게 유지 (삼평동 / 백현동)