In [1]:
import pandas as pd
import glob
import os

In [11]:
df[df['정류소ID'] == 206000616]

           승하차일자 관할관청      정류소ID   정류소번호     정류소명  승차합계  초승  환승  하차  bus_date
7300    20230201  성남시  206000616  7556.0  보평중고등학교    94  89   5  48  20230201
31803   20230202  성남시  206000616  7556.0  보평중고등학교    78  75   3  57  20230202
56284   20230203  성남시  206000616  7556.0  보평중고등학교    70  69   1  41  20230203
80647   20230204  성남시  206000616  7556.0  보평중고등학교    42  42   0  28  20230204
104071  20230205  성남시  206000616  7556.0  보평중고등학교    24  24   0  32  20230205
127240  20230206  성남시  206000616  7556.0  보평중고등학교    67  66   1  38  20230206
151784  20230207  성남시  206000616  7556.0  보평중고등학교    62  61   1  45  20230207
176264  20230208  성남시  206000616  7556.0  보평중고등학교    81  79   2  50  20230208
200786  20230209  성남시  206000616  7556.0  보평중고등학교    71  68   3  43  20230209
225324  20230210  성남시  206000616  7556.0  보평중고등학교    68  65   3  37  20230210
249656  20230211  성남시  206000616  7556.0  보평중고등학교    32  31   1  24  20230211
273152  20230212  성남시  206000616  7556.0  보평중고등학교    30  30   0  24  20230212
296345  20230213  성남시  206000616  7556.0  보평중고등학교    73  68   5  45  20230213
320904  20230214  성남시  206000616  7556.0  보평중고등학교    76  73   3  57  20230214
345465  20230215  성남시  206000616  7556.0  보평중고등학교    76  72   4  39  20230215
370001  20230216  성남시  206000616  7556.0  보평중고등학교    84  81   3  53  20230216
394552  20230217  성남시  206000616  7556.0  보평중고등학교    78  77   1  39  20230217
418987  20230218  성남시  206000616  7556.0  보평중고등학교    56  56   0  36  20230218
442452  20230219  성남시  206000616  7556.0  보평중고등학교    35  34   1  35  20230219
465679  20230220  성남시  206000616  7556.0  보평중고등학교    74  71   3  40  20230220
490290  20230221  성남시  206000616  7556.0  보평중고등학교    73  69   4  33  20230221
514814  20230222  성남시  206000616  7556.0  보평중고등학교    89  88   1  41  20230222
539409  20230223  성남시  206000616  7556.0  보평중고등학교    63  62   1  44  20230223
564020  20230224  성남시  206000616  7556.0  보평중고등학교    65  64   1  48  20230224
588540  20230225  성남시  206000616  7556.0  보평중고등학교    32  30   2  38  20230225
612203  20230226  성남시  206000616  7556.0  보평중고등학교    29  29   0  29  20230226
635486  20230227  성남시  206000616  7556.0  보평중고등학교    63  60   3  34  20230227
660222  20230228  성남시  206000616  7556.0  보평중고등학교    79  77   2  52  20230228

In [32]:
folder_3 = r'C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2023_D-45\CARD_STATION45_202303'

files = glob.glob(os.path.join(folder_3, '*.csv.gz'))

df_list = []

for f in files:
    # 압축파일 바로 읽기
    with gzip.open(f, 'rt', encoding='cp949') as file:
        temp = pd.read_csv(file)
    
    # 파일명에서 날짜 추출
    date_str = os.path.basename(f).replace('CARD_STATION45_', '').replace('.csv.gz', '')
    
    # 날짜 컬럼 추가
    temp['bus_date'] = date_str
    
    df_list.append(temp)

# 하나로 합치기
df_3 = pd.concat(df_list, ignore_index=True)

# 저장
output_path = os.path.join(folder_3, 'bus_202303_all.csv')
df_3.to_csv(output_path, index=False, encoding='utf-8-sig')

print("완료:", output_path)

완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2023_D-45\CARD_STATION45_202303\bus_202303_all.csv

In [ ]:
import pandas as pd
import glob
import os
import gzip

base_folder = r'C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2024_D-45'

for month in range(1, 13):  # ⭐ 5월부터 시작
    folder = os.path.join(base_folder, f'CARD_STATION45_2023{month:02d}')
    
    files = glob.glob(os.path.join(folder, '*.csv.gz'))
    
    df_list = []

    for f in files:
        try:
            with gzip.open(f, 'rt', encoding='cp949') as file:
                temp = pd.read_csv(file)
            
            date_str = os.path.basename(f).replace('CARD_STATION45_', '').replace('.csv.gz', '')
            temp['bus_date'] = date_str
            
            df_list.append(temp)

        except Exception as e:
            print(f"에러 파일: {f}")
            print(e)

    # 👉 파일 없는 경우 방지
    if len(df_list) == 0:
        print(f"{month}월 데이터 없음")
        continue

    df = pd.concat(df_list, ignore_index=True)

    output_path = os.path.join(folder, f'bus_2023{month:02d}_all.csv')
    df.to_csv(output_path, index=False, encoding='utf-8-sig')

    print(f"{month}월 완료:", output_path)

5월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2023_D-45\CARD_STATION45_202305\bus_202305_all.csv
6월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2023_D-45\CARD_STATION45_202306\bus_202306_all.csv
7월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2023_D-45\CARD_STATION45_202307\bus_202307_all.csv
8월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2023_D-45\CARD_STATION45_202308\bus_202308_all.csv
9월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2023_D-45\CARD_STATION45_202309\bus_202309_all.csv
10월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2023_D-45\CARD_STATION45_202310\bus_202310_all.csv
11월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2023_D-45\CARD_STATION45_202311\bus_202311_all.csv
12월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2023_D-45\CARD_STATION45_202312\bus_202312_all.csv

In [59]:
import pandas as pd
import glob
import os
import gzip

base_folder = r'C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45'

for month in range(1, 13):
    folder = os.path.join(base_folder, f'CARD_STATION45_2025{month:02d}')
    
    files = glob.glob(os.path.join(folder, '*.csv.gz'))
    
    df_list = []

    for f in files:
        try:
            with gzip.open(f, 'rt', encoding='cp949') as file:
                temp = pd.read_csv(file)
            
            date_str = os.path.basename(f).replace('CARD_STATION45_', '').replace('.csv.gz', '')
            temp['bus_date'] = date_str
            
            df_list.append(temp)

        except Exception as e:
            print(f"에러 파일: {f}")
            print(e)

    if len(df_list) == 0:
        print(f"{month}월 데이터 없음")
        continue

    df = pd.concat(df_list, ignore_index=True)

    output_path = os.path.join(folder, f'bus_2025{month:02d}_all.csv')
    df.to_csv(output_path, index=False, encoding='utf-8-sig')

    print(f"{month}월 완료:", output_path)

1월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202501\bus_202501_all.csv
2월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202502\bus_202502_all.csv
3월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202503\bus_202503_all.csv
4월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202504\bus_202504_all.csv
5월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202505\bus_202505_all.csv
6월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202506\bus_202506_all.csv
7월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202507\bus_202507_all.csv
8월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202508\bus_202508_all.csv
9월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202509\bus_202509_all.csv
10월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202510\bus_202510_all.csv
11월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202511\bus_202511_all.csv
12월 완료: C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 정류소 별 승하차 인원 집계_2025_D-45\CARD_STATION45_202512\bus_202512_all.csv

In [11]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\cute3\OneDrive\Desktop\bus_Data\경기도 성남시_버스정류장_현황_20260408.csv',
    encoding='utf-8'  # 깨지면 utf-8 또는 euc-kr로 변경
)

df.head()

,시군구,행정동,정류장번호(ID),정류장명,상세위치,위도,경도,정류장설치유형,시내버스_경유노선번호,시외버스_경유노선번호,레드존여부,중앙차로여부,미세먼지 측정센서 설치여부,와이파이설치여부,안전비상벨설치여부,버스정보안내단말기(BIT) 유형,의자설치유형,바람막이설치여부,냉온풍기설치여부,공기청정기설치여부
0,성남시,시흥동,5001.0,판교제2테크노밸리,한국도로공사본사앞,37.411683,127.099350,쉘터형,"P9243(퇴근)(시내),5700A(시내),55(시내),P9242(퇴근)(시내),6...",해당없음,N,N,Y,Y,N,LED(5단18열),일반의자,N,N,N
1,성남시,시흥동,5002.0,판교제2테크노밸리,한국도로공사본사건너,37.411333,127.099733,쉘터형,"5600(시내),P9241(출근)(시내),P9243(출근)(시내),1009(시내),...",해당없음,N,N,N,Y,N,LED(5단18열),일반의자,N,N,N
2,성남시,시흥동,5003.0,동산마을입구,시흥지하차도변 성남방면,37.422467,127.101233,지주형,"9800(시내),9409(서울),9400(시내)",해당없음,N,N,N,N,N,LED(3단6열),미설치,N,N,N
3,성남시,시흥동,5004.0,동산마을입구,시흥지하차도변 서울방면,37.422800,127.101400,쉘터형,"9400(시내),9800(시내)",해당없음,N,N,N,N,N,LED(3단6열),일반의자,N,N,N
4,성남시,고등동,5005.0,고등동행정복지센터.판교밸리자이아파트,고등동자치센터,37.428217,127.101650,쉘터형,"누리2(시내),1009(시내),6900(시내),342(시내),57(시내),5700A...",해당없음,N,N,Y,Y,Y,LCD(가로형 32''),일반의자,N,Y,Y

In [6]:
result = df[df['정류장명'] == 'AK플라자2층']

result

,시군구,행정동,정류장번호(ID),정류장명,상세위치,위도,경도,정류장설치유형,시내버스_경유노선번호,시외버스_경유노선번호,레드존여부,중앙차로여부,미세먼지 측정센서 설치여부,와이파이설치여부,안전비상벨설치여부,버스정보안내단말기(BIT) 유형,의자설치유형,바람막이설치여부,냉온풍기설치여부,공기청정기설치여부
954,성남시,서현1동,7387.0,AK플라자2층,AK플라자2층(백화점포함시설),37.384567,127.1238,쉘터형,"3-2(마을),3(마을),3-1(마을),520(시내)",해당없음,N,N,N,N,N,LED(3단6열)(양면),일반의자,N,N,N

버스

In [12]:
import pandas as pd

df_1 = pd.read_csv(
    r'C:/Users/cute3/OneDrive/Desktop/bus_Data/bus_행정동_all.csv.csv',
    encoding='utf-8'  # 깨지면 utf-8 또는 euc-kr로 변경
)

df.head()

C:\Users\cute3\AppData\Local\Temp\ipykernel_28868\2924254117.py:3: DtypeWarning: Columns (0: 정류소번호) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1 = pd.read_csv(

,시군구,행정동,정류장번호(ID),정류장명,상세위치,위도,경도,정류장설치유형,시내버스_경유노선번호,시외버스_경유노선번호,레드존여부,중앙차로여부,미세먼지 측정센서 설치여부,와이파이설치여부,안전비상벨설치여부,버스정보안내단말기(BIT) 유형,의자설치유형,바람막이설치여부,냉온풍기설치여부,공기청정기설치여부
0,성남시,시흥동,5001.0,판교제2테크노밸리,한국도로공사본사앞,37.411683,127.099350,쉘터형,"P9243(퇴근)(시내),5700A(시내),55(시내),P9242(퇴근)(시내),6...",해당없음,N,N,Y,Y,N,LED(5단18열),일반의자,N,N,N
1,성남시,시흥동,5002.0,판교제2테크노밸리,한국도로공사본사건너,37.411333,127.099733,쉘터형,"5600(시내),P9241(출근)(시내),P9243(출근)(시내),1009(시내),...",해당없음,N,N,N,Y,N,LED(5단18열),일반의자,N,N,N
2,성남시,시흥동,5003.0,동산마을입구,시흥지하차도변 성남방면,37.422467,127.101233,지주형,"9800(시내),9409(서울),9400(시내)",해당없음,N,N,N,N,N,LED(3단6열),미설치,N,N,N
3,성남시,시흥동,5004.0,동산마을입구,시흥지하차도변 서울방면,37.422800,127.101400,쉘터형,"9400(시내),9800(시내)",해당없음,N,N,N,N,N,LED(3단6열),일반의자,N,N,N
4,성남시,고등동,5005.0,고등동행정복지센터.판교밸리자이아파트,고등동자치센터,37.428217,127.101650,쉘터형,"누리2(시내),1009(시내),6900(시내),342(시내),57(시내),5700A...",해당없음,N,N,Y,Y,Y,LCD(가로형 32''),일반의자,N,Y,Y

In [13]:
df_1

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
0,2023-01-01,성남시,성남동,205000120,6163.0,(구)성남동주민센터,103,99,4,106
1,2023-01-01,성남시,서현1동,206000436,7387.0,AK플라자2층,353,203,150,454
2,2023-01-01,성남시,삼평동,206000677,7034.0,H스퀘어.삼환하이펙스,1,1,0,25
3,2023-01-01,성남시,삼평동,206000677,7034.0,H스퀘어.삼환하이펙스,1,1,0,25
4,2023-01-01,성남시,삼평동,206000678,7479.0,H스퀘어.삼환하이펙스,15,14,1,2
...,...,...,...,...,...,...,...,...,...,...
2058745,2025-12-31,성남시,복정동,204000234,05299,힐스테이트위례정문,17,17,0,49
2058746,2025-12-31,성남시,복정동,204000201,05298,힐스테이트위례후문.위례한빛초등학교,27,26,1,19
2058747,2025-12-31,성남시,운중동,206000854,07830,힐스테이트판교엘포레4단지,472,466,6,153
2058748,2025-12-31,성남시,운중동,206000472,07821,힐스테이트판교엘포레6단지,140,137,3,83
2058749,2025-12-31,성남시,운중동,206000646,07820,힐스테이트판교엘포레6단지.판교SK뷰테라스,258,258,0,59

In [16]:
df_1.to_csv(
    'bus_plz.csv',
    index=False,
    encoding='utf-8-sig'
)

In [14]:
df_1[df_1['행정동'].isnull()]

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
17,2023-01-01,성남시,NaN,206000855,7822.0,SK.금강테라스하우스,11,10,1,24
48,2023-01-01,성남시,NaN,204000001,5008.0,고등동우체국.성남농협대왕지점,89,60,29,178
84,2023-01-01,성남시,NaN,204000256,5221.0,교보문고(마을),11,11,0,30
94,2023-01-01,성남시,NaN,205000008,6076.0,구서고.금상초교,389,378,11,244
95,2023-01-01,성남시,NaN,205000160,6074.0,구서고.금상초교,317,303,14,332
...,...,...,...,...,...,...,...,...,...,...
2058599,2025-12-31,성남시,NaN,205000016,06025,하대원동행정복지센터.영성중.검단초,406,360,46,686
2058600,2025-12-31,성남시,NaN,205000152,06024,하대원동행정복지센터.영성중.검단초,731,688,43,352
2058647,2025-12-31,성남시,NaN,204000070,05151,한국폴리텍대학.성남문화예술교육센터,27,23,4,37
2058648,2025-12-31,성남시,NaN,204000080,05149,한국폴리텍대학.성남문화예술교육센터,8,4,4,36
2058688,2025-12-31,성남시,NaN,206000342,07318,현대노블리스,0,0,0,12

In [6]:
null_stops = (
    df_1[df_1['행정동'].isnull()][['정류소명']]
    .drop_duplicates()
    .sort_values('정류소명')
)

null_stops

                       정류소명
590062           (임시)금토동삼거리
17              SK.금강테라스하우스
1104425          고기3리.유원지입구
1104426               고기동마을
1104428              고기초등학교
...                     ...
1637     한양수자인성남마크뷰.황성게이트볼장
1644       헬스케어혁신파크.(구)가스공사
1738488              현대노블리스
1685        힐스테이트판교엘포레6단지후문
769538                  NaN

[138 rows x 1 columns]

In [7]:
df_1[df_1['정류소ID'] == 206000616]

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
526,2023-01-01,성남시,NaN,206000616,7556.0,보평중고등학교,16,16,0,22
2224,2023-01-02,성남시,NaN,206000616,7556.0,보평중고등학교,72,68,4,55
3938,2023-01-03,성남시,NaN,206000616,7556.0,보평중고등학교,80,78,2,53
5653,2023-01-04,성남시,NaN,206000616,7556.0,보평중고등학교,69,66,3,52
7364,2023-01-05,성남시,NaN,206000616,7556.0,보평중고등학교,74,73,1,50
...,...,...,...,...,...,...,...,...,...,...
2053477,2025-12-29,성남시,삼평동,206000616,07556,성남역.보평중고등학교,187,157,30,88
2055587,2025-12-30,성남시,백현동,206000616,07556,성남역.보평중고등학교,194,168,26,104
2055588,2025-12-30,성남시,삼평동,206000616,07556,성남역.보평중고등학교,194,168,26,104
2057688,2025-12-31,성남시,백현동,206000616,07556,성남역.보평중고등학교,223,184,39,82
2057689,2025-12-31,성남시,삼평동,206000616,07556,성남역.보평중고등학교,223,184,39,82

In [21]:
df_1[df_1['정류소명'] == '보평중고등학교']

             승하차일자 관할관청  행정동      정류소ID   정류소번호     정류소명  승차합계   초승  환승   하차
526     2023-01-01  성남시  NaN  206000616  7556.0  보평중고등학교    16   16   0   22
527     2023-01-01  성남시  NaN  206000617  7557.0  보평중고등학교     8    5   3   34
2224    2023-01-02  성남시  NaN  206000616  7556.0  보평중고등학교    72   68   4   55
2225    2023-01-02  성남시  NaN  206000617  7557.0  보평중고등학교    34   31   3   62
3938    2023-01-03  성남시  NaN  206000616  7556.0  보평중고등학교    80   78   2   53
...            ...  ...  ...        ...     ...      ...   ...  ...  ..  ...
780563  2024-03-27  성남시  NaN  206000617  7557.0  보평중고등학교    49   46   3  110
782319  2024-03-28  성남시  NaN  206000616  7556.0  보평중고등학교   147  144   3   76
782320  2024-03-28  성남시  NaN  206000617  7557.0  보평중고등학교    62   59   3   92
784066  2024-03-29  성남시  NaN  206000616  7556.0  보평중고등학교   115  113   2   52
784067  2024-03-29  성남시  NaN  206000617  7557.0  보평중고등학교    58   50   8  102

[904 rows x 10 columns]

In [15]:
df_1[df_1['정류소명'].isnull()]

             승하차일자 관할관청  행정동      정류소ID   정류소번호 정류소명  승차합계   초승   환승   하차
769538  2024-03-20  성남시  NaN  206000305  7159.0  NaN    75   74    1   77
769539  2024-03-20  성남시  NaN  206000314  7303.0  NaN    99   86   13   66
769540  2024-03-20  성남시  NaN  206000530  7487.0  NaN   621  312  309  529
769541  2024-03-20  성남시  NaN  206000537  7420.0  NaN   381  336   45  305
769542  2024-03-20  성남시  NaN  206000616  7556.0  NaN   148  148    0   52
769543  2024-03-20  성남시  NaN  206000617  7557.0  NaN    79   76    3  113

In [9]:
## 정류소명과 행정동이 모두 nan값일떄

# 날짜형 변환
df_1['승하차일자'] = pd.to_datetime(df_1['승하차일자'])

# -------------------------------------------------
# 1. 206000305 / 7159
# 2. 206000314 / 7303
# -------------------------------------------------
mask_group1 = (
    (
        (pd.to_numeric(df_1['정류소ID'], errors='coerce') == 206000305) &
        (pd.to_numeric(df_1['정류소번호'], errors='coerce') == 7159)
    )
    |
    (
        (pd.to_numeric(df_1['정류소ID'], errors='coerce') == 206000314) &
        (pd.to_numeric(df_1['정류소번호'], errors='coerce') == 7303)
    )
)

# 2023
mask_2023 = (
    mask_group1 &
    (df_1['승하차일자'].dt.year == 2023)
)

df_1.loc[
    mask_2023 & df_1['정류소명'].isnull(),
    '정류소명'
] = '아름마을.이매고교.효성선경아파트.하나은행'

df_1.loc[
    mask_2023 & df_1['행정동'].isnull(),
    '행정동'
] = '이매2동'

# 2024
mask_2024 = (
    mask_group1 &
    (df_1['승하차일자'].dt.year == 2024)
)

df_1.loc[
    mask_2024 & df_1['정류소명'].isnull(),
    '정류소명'
] = '성남역.이매고교.아름마을.효성선경아파트'

df_1.loc[
    mask_2024 & df_1['행정동'].isnull(),
    '행정동'
] = '이매2동'


# -------------------------------------------------
# 3. 206000530 / 7487
# -------------------------------------------------
mask_group2 = (
    (pd.to_numeric(df_1['정류소ID'], errors='coerce') == 206000530) &
    (pd.to_numeric(df_1['정류소번호'], errors='coerce') == 7487)
)

mask_2023 = mask_group2 & (df_1['승하차일자'].dt.year == 2023)

df_1.loc[
    mask_2023 & df_1['정류소명'].isnull(),
    '정류소명'
] = '백현마을2단지'

df_1.loc[
    mask_2023 & df_1['행정동'].isnull(),
    '행정동'
] = '백현동'

mask_2024 = mask_group2 & (df_1['승하차일자'].dt.year == 2024)

df_1.loc[
    mask_2024 & df_1['정류소명'].isnull(),
    '정류소명'
] = '성남역.백현마을2단지'

df_1.loc[
    mask_2024 & df_1['행정동'].isnull(),
    '행정동'
] = '백현동'


# -------------------------------------------------
# 4. 206000537 / 7420
# -------------------------------------------------
mask_group3 = (
    (pd.to_numeric(df_1['정류소ID'], errors='coerce') == 206000537) &
    (pd.to_numeric(df_1['정류소번호'], errors='coerce') == 7420)
)

mask_2023 = mask_group3 & (df_1['승하차일자'].dt.year == 2023)

df_1.loc[
    mask_2023 & df_1['정류소명'].isnull(),
    '정류소명'
] = '백현마을3단지'

df_1.loc[
    mask_2023 & df_1['행정동'].isnull(),
    '행정동'
] = '백현동'

mask_2024 = mask_group3 & (df_1['승하차일자'].dt.year == 2024)

df_1.loc[
    mask_2024 & df_1['정류소명'].isnull(),
    '정류소명'
] = '성남역.백현마을3단지'

df_1.loc[
    mask_2024 & df_1['행정동'].isnull(),
    '행정동'
] = '백현동'


# -------------------------------------------------
# 5. 206000616 / 7556
# 6. 206000617 / 7557
# -------------------------------------------------
mask_group4 = (
    (
        (pd.to_numeric(df_1['정류소ID'], errors='coerce') == 206000616) &
        (pd.to_numeric(df_1['정류소번호'], errors='coerce') == 7556)
    )
    |
    (
        (pd.to_numeric(df_1['정류소ID'], errors='coerce') == 206000617) &
        (pd.to_numeric(df_1['정류소번호'], errors='coerce') == 7557)
    )
)

# 2023
mask_2023 = mask_group4 & (df_1['승하차일자'].dt.year == 2023)

df_1.loc[
    mask_2023 & df_1['정류소명'].isnull(),
    '정류소명'
] = '보평중고등학교'

# 행정동은 기존 값 유지
# NaN인 경우만 직접 확인 후 수기 입력 추천

# 2024
mask_2024 = mask_group4 & (df_1['승하차일자'].dt.year == 2024)

df_1.loc[
    mask_2024 & df_1['정류소명'].isnull(),
    '정류소명'
] = '성남역.보평중고등학교'

# 행정동은 그대로 유지


# 최종 확인
print(df_1[['정류소명', '행정동']].isnull().sum())

정류소명        0
행정동     63298
dtype: int64

- 정류소ID 206000305 / 정류소번호 7159.0
    - 2023년: 정류소명 → 아름마을.이매고교.효성선경아파트.하나은행, 행정동 → 이매2동
    - 2024년: 정류소명 → 성남역.이매고교.아름마을.효성선경아파트, 행정동 → 이매2동 
- 정류소ID 206000314 / 정류소번호 7303.0
  - 2023년: 정류소명 → 아름마을.이매고교.효성선경아파트.하나은행, 행정동 → 이매2동
  - 2024년: 정류소명 → 성남역.이매고교.아름마을.효성선경아파트, 행정동 → 이매2동
- 정류소ID 206000530 / 정류소번호 7487.0
  - 2023년: 정류소명 → 백현마을2단지, 행정동 → 백현동
  - 2024년: 정류소명 → 성남역.백현마을2단지, 행정동 → 백현동
- 정류소ID 206000537 / 정류소번호 7420.0
  - 2023년: 정류소명 → 백현마을3단지, 행정동 → 백현동
  - 2024년: 정류소명 → 성남역.백현마을3단지, 행정동 → 백현동
- 정류소ID 206000616 / 정류소번호 7556.0
  - 2023년: 정류소명 → 보평중고등학교
    - 앞쪽 정류장 행정동 → 삼평동
    - 뒤쪽 정류장 행정동 → 백현동
  - 2024년: 정류소명 → 성남역.보평중고등학교
   - 행정동은 동일하게 유지 (삼평동 / 백현동)
- 정류소ID 206000617 / 정류소번호 7557.0
  - 2023년: 정류소명 → 보평중고등학교
    - 앞쪽 정류장 행정동 → 삼평동
    - 뒤쪽 정류장 행정동 → 백현동
- 2024년: 정류소명 → 성남역.보평중고등학교
   - 행정동은 동일하게 유지 (삼평동 / 백현동)

In [66]:
df_1[df_1['행정동'].isnull()]['정류소명'].value_counts()

Series([], Name: count, dtype: int64)

In [65]:
null_stops = (
    df_1[df_1['행정동'].isnull()][['정류소명']]
    .drop_duplicates()
    .sort_values('정류소명')
    .reset_index(drop=True)
)

null_stops.head(30)

Empty DataFrame
Columns: [정류소명]
Index: []

In [51]:
## 성남시가 아닌 행
df_1 = df_1[
    ~df_1['정류소명'].isin([
        '고기3리.유원지입구',
        '고기동마을',
        '고기초등학교'
    ])
]

In [56]:
dong_map = {
    '(임시)금토동삼거리': '금토동',
    'SK.금강테라스하우스': '대장동',
    '고등동우체국.성남농협대왕지점': '고등동',
    '고등동행정복지센터.성남농협대왕지점': '고등동',
    '공단치안센터.근로자종합복지관': '상대원동',
    '곽여성병원(마을)': '태평동',
    '교보문고(마을)': '백현동',
    '구미공원.불곡초등학교': '구미동',
    '구미동행정복지센터': '구미동',
    '구서고.금상초교': '금광동',
    '국은교앞': '운중동',
    '금상초교.이편한세상3단지': '금광동',
    '금상초교.이편한세상5단지': '금광동',
    '나라기록관.코이카': '시흥동',
    '남한산성공원입구': '양지동',
    '남한산성공원입구.양지파출소': '양지동',
    '노블빌리지': '구미동',
    '농수산물센터사거리': '구미동',
    '농수산물센터사거리.LG트윈하우스': '구미동',
    '단대오거리역.성남시박물관': '신흥동',
    '단대오거리역.세이브존.성남시박물관': '신흥동',
    '대하초등학교.중원유스센터': '하대원동',
    '더블트리바이힐튼호텔.잡월드': '정자동',
    '동국대한방병원.신성아파트.수내도서관': '수내동',
    '동원동종점.모드니': '동원동',
    '목련마을SK아파트.성남시차량등록사업소': '야탑동',
    '무지개도서관.구미파출소.건영아파트': '구미동',
    '무지개마을사거리': '구미동',
    '백현동종점': '백현동'
}

df_1['행정동'] = df_1['행정동'].fillna(
    df_1['정류소명'].map(dong_map)
)

In [58]:
dong_map_update = {
    '다이소앞': '구미동',
    '벽산아파트': '수내동',
    '보평중고등학교': '백현동',
    '봇들마을7.8단지.롯데마트판교점': '삼평동',
    '분당경영고.한라아파트': '금곡동',
    '분당아테나': '수내동',
    '분당아테라': '수내동',
    '사송동.한국수자원공사': '사송동',
    '사송동.한국수자원공사(마을)': '사송동',
    '상대원119안전센터.성남공단우체국': '상대원동',
    '새마을연수원입구': '율동',
    '서현유스센터.양영디지털고등학교': '서현동',
    '선경아파트.성남중원경찰서.중원구보건소': '상대원동',
    '선텍시티2차': '상대원동',
    '성남고등공공주택지구.동편': '고등동',
    '성남고등공공주택지구.서편': '고등동',
    '성남금융고': '야탑동',
    '성남금융고.중탑초교': '야탑동',
    '성남냉동': '하대원동',
    '성남농협대왕지점.고등동우체국': '고등동',
    '성남물빛정원남측.노블빌리지': '구미동',
    '성남물빛정원서측.한국토지주택공사': '구미동',
    '성남북초등학교.산성동행정복지센터.산성역자이4단지': '산성동',
    '성남시근로자종합복지관': '상대원동',
    '성남시여성비전센터.삼성생명.한국사회적기업진흥원': '태평동',
    '성남시여성비전센터.성남수정새마을금고.한국사회적기업진흥원': '태평동',
    '성남시의료원.신흥1동행정복지센터.성남아트리움': '신흥동',
    '성남시장례문화사업소': '갈현동',
    '성남시장례문화사업소.장례식장입구': '갈현동',
    '성남역': '백현동'
}

df_1['행정동'] = df_1['행정동'].fillna(
    df_1['정류소명'].map(dong_map_update)
)

In [60]:
dong_map_update2 = {
    '성남역': '백현동',
    '성남역.보평중고등학교': '백현동',
    '성남중원경찰서': '상대원동',
    '성남혜은학교.수정유스센터.산성역자이3단지': '신흥동',
    '성보경영고등학교': '단대동',
    '세이브존.성남시박물관': '신흥동',
    '셀레스빌아파트.포레스티아중문': '신흥동',
    '수내2동행정복지센터': '수내동',
    '수내고등학교.수내도서관': '수내동',
    '수정구청.산성역자이2단지': '신흥동',
    '수정구청.포레스티아서문': '신흥동',
    '수정초등학교': '수진동',
    '수진동성당': '수진동',
    '순환도시친환경세상순환자원홍보관': '석운동',
    '쉐보레분당서비스센터': '금곡동',
    '시흥동농협창고': '시흥동',
    '시흥사거리.고등공공주택지구': '시흥동',
    '신지교회': '성남동',
    '아튼빌아파트.중원유스센터': '하대원동',
    '에스콰이어': '상대원동',
    '옛근로자종합복지관': '성남동',
    '오리삼거리(마을)': '구미동',
    '우성아파트': '정자동',
    '위례31단지.위례포레샤인후문': '창곡동',
    '위례31단지정문': '창곡동',
    '위례동행정복지센터.위례보미리즌빌': '창곡동',
    '위례동행정복지센터.위례아트리버푸르지오': '창곡동',
    '위례자연앤래미안e편한세상.위례한빛중학교': '창곡동',
    '위례자연앤래미안e편한세상.위례힐스테이트': '창곡동',
    '위례자이아파트': '창곡동'
}

# 행정동 NULL만 채우기
df_1['행정동'] = df_1['행정동'].fillna(
    df_1['정류소명'].map(dong_map_update2)
)

# 왕재건설중기 행 삭제
df_1 = df_1[
    df_1['정류소명'] != '왕재건설중기'
]

In [62]:
dong_map_update3 = {
    '위례자이후문': '창곡동',
    '위례중앙초등학교': '창곡동',
    '위례포레샤인.위례31단지후문': '창곡동',
    '위례한빛고등학교': '창곡동',
    '위례한빛초.래미안.힐스테이트.한빛마을': '창곡동',
    '위례한빛초교.힐스테이트후문.한빛마을': '창곡동',
    '위례호반베르디움': '창곡동',
    '위례힐스테이트정문': '창곡동',
    '위례힐스테이트후문.위례한빛초등학교': '창곡동',
    '이노밸리.포스코ICT': '삼평동',
    '이매역.진흥아파트.동신아파트': '이매동',
    '이우중고등학교.주성카센타': '동원동',
    '이지더원.삼평동행정복지센터': '삼평동',
    '이편한세상5단지': '금광동',
    '이편한세상금빛그랑메종': '금광동',
    '자연앤센트럴자이': '창곡동',
    '자연앤센트럴자이정문': '창곡동',
    '정자유스센터.분당클리닉': '정자동',
    '주공12단지': '구미동',
    '주공7단지앞.치매안심센터': '정자동',
    '주공7단지앞.한솔종합사회복지관.치매안심센터': '정자동',
    '중동고개.제일초교': '중앙동',
    '중앙동사거리': '중앙동',
    '중원구청.성남소방서': '성남동',
    '진로아파트': '단대동',
    '창조밸리교': '금곡동',
    '창조밸리교(경유)': '금곡동',
    '청솔마을.계룡아파트': '금곡동',
    '청솔마을.화인아파트': '금곡동',
    '파크뷰아파트.정자유스센터': '정자동'
}

df_1['행정동'] = df_1['행정동'].fillna(
    df_1['정류소명'].map(dong_map_update3)
)

In [64]:
dong_map_update4 = {
    '판교고.송현초.삼평동행정복지센터': '삼평동',
    '판교대장초?중학교': '대장동',
    '판교더샵포레스트11단지': '대장동',
    '판교청소년수련관.판교종합사회복지관': '판교동',
    '판교퍼스트힐푸르지오2단지': '대장동',
    '포레스티아서문.신흥2동행정복지센터.산성역자이2단지': '신흥동',
    '푸른마을신성아파트.수내도서관': '수내동',
    '하대원동행정복지센터.영성중.검단초': '하대원동',
    '한국폴리텍대학.성남문화예술교육센터': '산성동',
    '한양수자인성남마크뷰.황성게이트볼장': '금광동',
    '헬스케어혁신파크.(구)가스공사': '정자동',
    '현대노블리스': '구미동',
    '힐스테이트판교엘포레6단지후문': '대장동'
}

df_1['행정동'] = df_1['행정동'].fillna(
    df_1['정류소명'].map(dong_map_update4)
)

In [70]:
df_1.to_csv(
    'bus_final.csv',
    index=False,
    encoding='utf-8-sig'
)